
import 'package:hive_flutter/hive_flutter.dart';
/// import autogenerated code (generated by the hive_generator and build_runner)
part 'employee.g.dart';

/// Set hive type id  and field names using annotations
@HiveType(typeId: 0)
class Employee{
  @HiveField(1)
  late String fullName;
  @HiveField(2)
  late String phoneNumber;
  @HiveField(3)
  late String email;
  @HiveField(4)
  late String position;
  @HiveField(5)
  late double salary;

  Employee(
    this.fullName,
    this.phoneNumber,
    this.email,
    this.position,
    this.salary
  );

  /// for creating empty employee objects
  /// sets string fields to empty and [salary] to -1
  Employee.empty(){
    fullName = '';
    phoneNumber = '';
    email = '';
    position = '';
    salary = -1; /// -1 serves as a flag that salary hasn't been initialized
  }

}